const comments = {
  a:{
    user: '1',
    id:'a',
    content: "I think the new phone is another winner from Apple. Sure, it didn’t reinvent the wheel, but the new design is sleek, the new processor speed will be a game changer for me, the camera is like a real SLR in your pocket, and the whole headphone thing is about moving to a wireless future where everything is easier. I’m impressed! OK @jasmine_p_smith, your turn. :smile:",
    likes: 28,
    liked: false,
    reactions: [{name: ':heart:', count: 1}, {name: ':ok_woman:',count: 2}],
    upvotes: 87,
    downvotes: 10,
    upvoted: false,
    staffPick: true,
    showProfile:true,
    pubdate: 3600000,
    replies: ['f','j']
  },
  b:{
    user: '1',
    id:'b',
    content: 'Sure, Apple makes Bluetooth headphones, but this is about more than that. Apple’s focus for a long time has been on high-quality music. You just can’t get that from 40-year-old technology. :music_notes: :thumbs_up:',
    likes: 11,
    liked: false,
    reactions: [{name: ':heart:', count: 1}, {name: ':ok_woman:',count: 2}],
    upvotes: 45,
    downvotes: 0,
    upvoted: false,
    pubdate: 7200000
  },
  c:{
    user: '2',
    id:'c',
    content: "This is one of the worst announcements I’ve seen from Apple. There’s just nothing new here. I use a Mac and was thinking about switching from Android, but after this announcement, I simply don’t see why I should.",
    likes: 4,
    liked: false,
    reactions: [{name: ':heart:', count: 1}, {name: ':ok_woman:',count: 2}],
    upvotes: 82,
    downvotes: 22,
    upvoted: false,
    staffPick: true,
    pubdate: 7200000,
    replies: ['g','e']
  },
  d:{
    user: '4',
    id:'d',
    content: "I’m a little underwhelmed, but I’ll probably buy it anyway. I’ve bought the last three iPhones, and this one seems a good enough upgrade on what I’m using now (6 plus). But I still don't see the value in the Watch.",
    likes: 7,
    liked: false,
    reactions: [{name: ':heart:', count: 1}, {name: ':ok_woman:',count: 2}],
    upvotes: 84,
    downvotes: 23,
    upvoted: false,
    staffPick: true,
    pubdate: 10000000
  },
  e:{
    user: '5',
    id:'e',
    content: "HAHAHAA You’re ridiculous. Android phones are a pile of $%^#& created for idiots to waste money on",
    likes: 0,
    liked: false,
    reactions: [{name: ':heart:', count: 1}, {name: ':ok_woman:',count: 2}],
    upvotes: 1,
    downvotes: 15,
    upvoted: false,
    troll: true,
    reply:true,
    pubdate: 10200000
  },
  f:{
    user: '2',
    id:'f',
    content: ":laughing: I think we’ve been here before - it’s nothing that Android phones didn’t have two years ago, except for the no headphones thing. That’s the stupidest idea I’ve ever heard. Do you really think it makes sense?",
    likes: 9,
    liked: false,
    reactions: [{name: ':heart:', count: 1}, {name: ':ok_woman:',count: 2}],
    upvotes: 14,
    downvotes: 0,
    upvoted: false,
    replies:['h'],
    reply: true,
    pubdate: 15000000
  },
  g:{
    user: '3',
    id:'h',
    content: "How is your Android at syncing with your Mac?",
    likes: 24,
    liked: false,
    reactions: [{name: ':ok_woman:',count: 2}],
    upvotes: 22,
    downvotes: 0,
    upvoted: false,
    staffPick: true,
    reply:true,
    replies:['i'],
    pubdate: 25000000
  },
  h:{
    user: '1',
    id:'g',
    content: "Yes! See my comment below. It’s not as stupid as you think.",
    likes: 1,
    liked: false,
    reactions: [{name: ':heart:', count: 1}, {name: ':ok_woman:',count: 2}],
    upvotes: 30,
    downvotes: 15,
    reply: true,
    upvoted: false,
    pubdate: 20000000
  },
  i:{
    user: '2',
    id:'h',
    content: "It’s great! Very easy. And doesn’t need to use iTunes - which is one of the best things about it :smile:",
    likes: 24,
    liked: false,
    reactions: [{name: ':heart:', count: 1}],
    upvotes: 22,
    downvotes: 0,
    upvoted: false,
    staffPick: true,
    reply: true,
    pubdate: 25000000
  },
  j:{
    user: '6',
    id: 'j',
    content: "You f#$%*ing Apple fanboys are nothing but drones.",
    likes: 0,
    liked: false,
    reactions: [{name: ':heart:', count: 1}],
    upvotes: 10,
    downvotes: 20,
    upvoted: false,
    troll: true,
    reply: true,
    pubdate: 28000000
  }
};

export default comments;
